<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHoSFYe5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHoSFYe5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHoSFYe5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHoSFYe5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHoSFYe5\App_KernelDevDebugContainer([
    'container.build_hash' => 'HoSFYe5',
    'container.build_id' => 'b25296bc',
    'container.build_time' => 1677072745,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHoSFYe5');
