<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSX2FFV5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSX2FFV5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSX2FFV5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSX2FFV5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSX2FFV5\App_KernelDevDebugContainer([
    'container.build_hash' => 'SX2FFV5',
    'container.build_id' => 'd6627d90',
    'container.build_time' => 1677061205,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSX2FFV5');
